### ISSUE TITLE
client crash: NPE in DragonAPI getDefaultPitch

### ISSUE THREAD

**Issue by keturn** [breakinblocks/nutsandbolts#145] opened 2017-04-02 17:47 UTC
Can't reproduce this one on command, presumably it's triggered by something in the area but I don't know what, but I have seven client crash logs with this in it now.

```
	at Reika.DragonAPI.Instantiable.Event.Client.SoundPitchEvent.getDefaultPitch(SoundPitchEvent.java:38)
	at Reika.DragonAPI.Instantiable.Event.Client.SoundPitchEvent.<init>(SoundPitchEvent.java:32)
	at Reika.DragonAPI.Instantiable.Event.Client.SoundPitchEvent.fire(SoundPitchEvent.java:42)
```

Full crash report at https://gist.github.com/keturn/de9b3bf4da3ad789b9568c8875787371

**Comment by keturn** [comment] 2017-04-04 02:48
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1389

I can see two routes from here:

One is to try to find what mod or sound it is that's sending something through as null, and try to correct that. That information doesn't look to be in the crash report, but something related may have appeared elsewhere in the client log.

The other is to try to put it back in DragonAPI's court, because if it's an event from some other mod, and the only mods in the pack that explicitly use DragonAPI are Reika's, then ... well, if DragonAPI is going to go through the trouble of hooking into events that others did not ask it to meddle in, then it needs to be prepared to at least _not crash the entire program_ when those hooks get called back.

**Comment by Saereth** [comment] 2017-04-04 12:00
Minecraft/forge doesnt crash with a null sound, dragonapi does, and its a simple fix on Reikas end. He's pretty stubborn though so I wouldn't expect him to do anything about it when he's already decided it's not his problem. Going mod by mod to try and pin it down is the solution but it's particularly annoying to track down because its a very rare crash and no one as of yet has been able to reproduce it reliably to give any indication of what mod might be causing it. Soooo, even if you start randomly removing mods it'd be hard to say with 100% certainly that its fixed each time.

**Comment by Saereth** [comment] 2017-04-04 15:55
I'll go ahead and label this under wontfix for now then unless someone gets more information

**Closed by Saereth** 2017-04-04 15:55 UTC

**Comment by keturn** [comment] 2017-04-04 16:17
On the one hand, should you accept any garbage input and try to make it do something useful? No, as you've said, that's likely to only propagate the garbage further through the system.

On the other hand, the cases in which it is acceptable to _crash the entire program_ — breaking the user out of the game and, in a pack like this, making the user wait at least five minutes until they've restarted the thing — that sort of failure mode should be reserved for when you _absolutely cannot continue_, where the player or client would be left in an unusable state.

It is unfortunate that the API allows events to come through with Nulls in them, and that your programming language delivers these as arguments to your function even though it is declared ISound, and that there's not something higher-up in the event loop that says "NPE? oh I guess we'll just write a crashlog and drop that event handler",

but if you can't fix any of _those_ things, it seems irresponsible say that means you won't fix _anything_.

**Comment by ReikaKalseki** [comment] 2017-04-04 19:59
See my reply to the issue on my tracker.
